# Generated by Django 5.1.5 on 2025-02-27 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва акції')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створений')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлений')),
            ],
            options={
                'verbose_name': 'Акція',
                'verbose_name_plural': 'Акції',
            },
        ),
        migrations.CreateModel(
            name='AdvertisingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/advertising_images/', verbose_name='Рекламний банер')),
                ('advertising', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.advertising', verbose_name='Акція')),
            ],
            options={
                'verbose_name': 'Зображення акції',
                'verbose_name_plural': 'Зображення акцій',
            },
        ),
    ]
