# Generated by Django 5.1.5 on 2025-02-27 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisingimage',
            options={'ordering': ['id'], 'verbose_name': 'Зображення акції', 'verbose_name_plural': 'Зображення акцій'},
        ),
        migrations.AlterField(
            model_name='advertisingimage',
            name='advertising',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adv_image', to='main.advertising', verbose_name='Акція'),
        ),
    ]
