# Generated by Django 5.1.5 on 2025-02-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_advertisingimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertising',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання на акцію'),
        ),
    ]
