# Generated by Django 5.1.5 on 2025-02-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Місто/Село'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адреса доставки'),
        ),
    ]
