# Generated by Django 4.2.18 on 2025-03-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('In availability', 'В наявності'), ('Not in availability', 'Немає в наявності')], default='In availability', max_length=20, verbose_name='Наявність'),
        ),
    ]
